### ISSUE TITLE
Single issue without project ID

### ISSUE THREAD

**Issue by Ditchfuuu** [ubisoft/NGitLab#217]
Hi,

Just wondering if there's a way to retrieve a single issue using its ID (with no project ID) as shown in the [GitLab API docs here](https://docs.gitlab.com/ee/api/issues.html#single-issue) - I might be just missing something, in which case apologies!

Thanks for maintaining this, it's been really useful in our project ⭐ .

**Comment by meziantou** [comment]
Hi,

This is not supported yet.
You can submit a PR to add the method to [IIssueClient.cs](https://github.com/ubisoft/NGitLab/blob/main/NGitLab/IIssueClient.cs) if you want

**Comment by Ditchfuuu** [comment]
This has been added with #220
