### ISSUE TITLE
Add due date to Issue create/edit models

### ISSUE THREAD

**Issue by Ditchfuuu** [ubisoft/NGitLab#229]
I don't _think_ we can specify a due date when creating or editing an issue, is there a reason this is omitted or is it something I could look at adding?

**Comment by meziantou** [comment]
`DueDate` is only supported in the GET operations. You can submit a PR to add the `DueDate` property in [`IssueCreate.cs`](https://github.com/ubisoft/NGitLab/blob/main/NGitLab/Models/IssueCreate.cs), [`IssueEdit.cs`](https://github.com/ubisoft/NGitLab/blob/main/NGitLab/Models/IssueEdit.cs) and add a new test ([IssueTests.cs](https://github.com/ubisoft/NGitLab/blob/main/NGitLab.Tests/IssueTests.cs)).

**Comment by meziantou** [comment]
Closed by https://github.com/ubisoft/NGitLab/pull/230

**Comment by meziantou** [comment]
A new release is in progress: https://github.com/ubisoft/NGitLab/actions/runs/2332328680

Thanks for your contribution 🚀
