### ISSUE TITLE
Empty Commit

### ISSUE THREAD

**Issue by noxe** [ubisoft/NGitLab#258]
Hi, is it possible to create an empty commit (git commit --allow-empty) using this API Client?

thx

**Comment by jairbubbles** [comment]
Hi @noxe,

GitLab exposes [this API](https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions) to create commits which is exposed in NGitLab though `ICommitClient`.

I don't know if you can create empty commits, it would need some more testing.

**Comment by noxe** [comment]
Hi - thx for your reply - yes i found this - but since it requires actions and file paths i was not sure it is possible since they seems to be mandatory...

**Comment by louis-z** [comment]
> Hi - thx for your reply - yes i found this - but since it requires actions and file paths i was not sure it is possible since they seems to be mandatory...

Just confirmed that it is possible using `ICommitClient.Create(CommitCreate commit)`. The only things mandatory are `CommitCreate`'s `Branch` and `CommitMessage`.
