### ISSUE TITLE
Subgroups api missing or not readily visible

### ISSUE THREAD

**Issue by Blackclaws** [ubisoft/NGitLab#295]
I've been trying to get the subgroups for a group, however I don't see any other way than to get all groups and then filter by parent id. This seems a bit roundabout, seeing how gitlab does offer a list subgroup endpoint:

https://docs.gitlab.com/ee/api/groups.html#list-a-groups-subgroups

This endpoint is basically a scoped groups endpoint.
This plus the list descendant groups would be nice additions. We heavily structure our projects in subgroups within subgroups so having something to work with that would be nice.

**Comment by meziantou** [comment]
This endpoint is not implemented in NGitLab yet, but it would be a nice addition.

We have no plan to implement it ourself at the moment. If someone from the community submit a Pull Request, we'll be happy to review it. If you need help to create the PR, we can assist you!

**Comment by Rimgelair** [comment]
@meziantou I was hoping to submit a PR to address this issue 😄 if possible!

**Comment by meziantou** [comment]
@Rimgelair Feel free to submit a PR!

**Comment by Rimgelair** [comment]
@meziantou I think that this issue can closed since PR #387 was merged.
