### ISSUE TITLE
Post the build status to a commit

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [ubisoft/NGitLab#313]
Couldn't work out in this client implementation if POST [/projects/:id/statuses/:sha](https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit ) was implemented within this library. 

Came to this library from a previous library which seems to not getting the latest API endpoints also https://github.com/nmklotas/GitLabApiClient/issues/219  

Cheers

**Comment by meziantou** [comment]
The endpoint is accessible using NGitLab: `IGitLabClient.GetCommitStatus(projectid).AddOrUpdate(...)`

**Comment by andrew-flatters-bliss** [comment]
Ah okay highly assumed the "Get" endpoints were read-only didn't spot the AddOrUpdate on the end. Cheers.
