### ISSUE TITLE
414 Request URI Too Large when updating a single file in the repository

### ISSUE THREAD

**Issue by nicolasbouchard-ubi** [ubisoft/NGitLab#381]
Hi/Bonjour!

I have with the FileClient.Update method of the API because it writes the file content directly in the URL query parameters. I think the parameter should be passed in the body instead. 

I can gladly do a PR for that but before I would like an active contributor to confirm if there's an actual reason for this behavior.

Thanks!

**Comment by meziantou** [comment]
Hi,

Maybe previous version of GitLab required the parameter to be in the query string. Or maybe someone wrongly implemented the method. 
If this is supported, feel free to create a PR that moves the content to the body.

Note that `CommitClient.Create` doesn't have this limitation.

**Comment by PMExtra** [comment]
I think it should be already fixed in #443.
