### ISSUE TITLE
Support  Project/Repository  commits filter

### ISSUE THREAD

**Issue by niltor** [ubisoft/NGitLab#429]
## What I have Tried

I find `GetCommitsRequest` model, but it doesn't contain all filter params!
```csharp
public class GetCommitsRequest
{
    internal const uint DefaultPerPage = 100;

    public string RefName { get; set; }

    public string Path { get; set; }

    public bool? FirstParent { get; set; }

    public int MaxResults { get; set; }

    public uint PerPage { get; set; } = DefaultPerPage;
}
``` 

## GitLab API Document:
[List repository commits](https://docs.gitlab.com/ee/api/commits.html#list-repository-commits)

![image](https://user-images.githubusercontent.com/8222201/232992706-2c8e26e9-1824-497e-bc62-b1b7389f6d18.png)

Just like picture above, there are many request  params which I need!

**Comment by meziantou** [comment]
The model is not complete (GitLab adds new parameter at each release). Feel free to submit a PR to add the missing parameters.
