### ISSUE TITLE
Missing License Information In Nuget metadata

### ISSUE THREAD

**Issue by LiorBanai** [ubisoft/NGitLab#480]
Hi,
Could the license information be added to the nuget information?
it is good to add it so it will be shown in Visual Studio nuget management.

for example,I use the following ```<PackageLicenseExpression>MIT</PackageLicenseExpression>``` in my nugets:

	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryType>git</RepositoryType>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

Also some tools can create auto generated report like (dotnet-project-licenses)  but right now those create missing entry:
![image](https://github.com/ubisoft/NGitLab/assets/36262995/532700f2-8baf-41ed-bb1d-61e15ec07c26)

**Comment by meziantou** [comment]
The license file is embedded in the nuget package and the nuspec is ok. So, the only change we could do is switching to a license expression instead of a license file.

**Comment by LiorBanai** [comment]
Yeah. the recommendation is to use license expression when the license is standard OSS license..
https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices
