### ISSUE TITLE
[Question] get related Issues for specific Issue.

### ISSUE THREAD

**Issue by LiorBanai** [ubisoft/NGitLab#482]
Hi,
Is there a way to get all related issues for a specific issues?
I normaly uses primary issues with "sub issues" linked to that one so this option to get it will be usefull to me for reporting.

**Comment by meziantou** [comment]
I think the call you need is <https://docs.gitlab.com/ee/api/issue_links.html#list-issue-relations>. This is not implemented in NGitLab, but PRs are welcomed.

**Comment by LiorBanai** [comment]
I'll look into it :)

**Comment by LiorBanai** [comment]
Hi @meziantou,
I have added support for reading linked issues. Unfortunately I have no idea how to implement the mocking implementation so I have return ``` Enumerable.Empty<Models.Issue>();```

I will submit PR soon if That acceptable solution regarding the mock.

**Comment by meziantou** [comment]
Thanks for the PR!
