### ISSUE TITLE
Webhooks / Subscription in Mock

### ISSUE THREAD

**Issue by mvarendorff2** [ubisoft/NGitLab#537]
In a project I am working on, we heavily use GitLab webhooks to automate our workflow. Now when writing tests, we wanted to incorporate these things as well.

I could not find a way to use NGitLab.Mock to listen for changes to manually call our webhook with the relevant data. Am I missing something? Does this exist, is there existing API that could be leveraged to make something like this?

Essentially what I would need is some stream or callback handler thing that allows me to get notified when an issue or a merge request or something alike changes and then call a certain function.

**Comment by meziantou** [comment]
NGitLab.Mock doesn't support webhooks. However, based on your needs, you can use the events on collections to detect when a change occurs (`INotifyCollectionChanged`).

**Comment by meziantou** [comment]
I'm not sure what it would take to support webhooks in tests. Feel free to share some ideas :)

**Comment by mvarendorff2** [comment]
The collection notifier is very close to what I need actually! If there was something like this to listen for the items in the collection to change, that would be immensely useful. So that I could listen for calls to, for instance, `gitLab.Issues.EditAsync`; the collection notifier does allow listening for `gitLab.Issues.CreateAsync` though!

I am unsure how that would look like in code but given some guidance I could look into making a PR!

**Comment by meziantou** [comment]
Implementing something that would allow simulating webhooks is more complicated as webhooks, most of the time, has the previous and new values. So, you can't only rely on IPropertyChanged / INotifyCollectionChanged.

I forgot to mention the `Server.ClientOperation` event that is raised for each method on a client. The event is currently empty, so you don't know which method is called, but we could add more data to it if needed.

**Comment by mvarendorff2** [comment]
What you mentioned about requiring the previous values definitely is true; we make lots of use of that to check in what ways the assignee or labels for example have changed to react to that accordingly.

Yeah, I saw `Server.ClientOperation` but couldn't find much use in the empty args indeed. What information would go in there? The way it's currently being invoked makes it quite difficult to pass any result-y sort of thing because the scope is always created before any action happens.

**Comment by mvarendorff2** [comment]
We ended up rolling our own stuff using Moq's Callback to intercept the calls relevant to us and simulating a webhook call to our endpoint. Given that this is probably very specialized, I'd close this, since we have found our way around.
