### ISSUE TITLE
Missing TimeStatsAsync for MergeRequests

### ISSUE THREAD

**Issue by DelphinRP** [ubisoft/NGitLab#538]
Hi everyone and thank you for this awesome library!

Currently it is possible to access time stats on issues:

```csharp
var timestats = await _gitLabClient.Issues.TimeStatsAsync(
  issue.ProjectId,
  issue.IssueId,
  CancellationToken.None);
```

The same does not work with merge requests as the `TimeStatsAsync` is missing:

```csharp
var timestats = await _gitLabClient.MergeRequests.TimeStatsAsync(
  mergeRequest.ProjectId,
  mergeRequest.Id,
  CancellationToken.None);
```

This API does not seem to exist. According to [GitLab documentation](https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests) the time stats are provided along with merge requests themselves.

Can the merge request model be extended with a `TimeStats` property or the client be extended with `TimeStatsAsync` method?

**Comment by meziantou** [comment]
Feel free to write a pull request to add the missing feature! (the change seems pretty simple)
