### ISSUE TITLE
Multiple files commit

### ISSUE THREAD

**Issue by pkenterlis** [ubisoft/NGitLab#619]
Hello, is there a way to perform a multi-file commit?
I need to create an initial commit with files from a zip file.

**Comment by wernersbacher** [comment]
Just use the commits API and create a list with several file create actions. [Check this example](https://github.com/ubisoft/NGitLab/blob/7c8fcfd00b3203b002b435702091a9a63c124d3d/NGitLab.Tests/CommitsTests.cs#L96) which uses the commits api for a single file.
