### ISSUE TITLE
Variable is missing new 'raw' flag

### ISSUE THREAD

**Issue by shell0r1** [ubisoft/NGitLab#662]
In the recent versions of GitLab (15.7+) a new 'raw' flag has been introduced along side of 'masked' and 'protected'.
The purpose of this flag is to be able to signal whether or not the variable value should be expanded or used raw.
When working with variables it would be helpful to have the possibility to set this, so we do not have to rely on the default value.

Docs:
https://about.gitlab.com/releases/2022/12/22/gitlab-15-7-released/#support-the--character-in-cicd-variables
https://gitlab.com/gitlab-org/gitlab/-/issues/17069
https://docs.gitlab.com/ee/api/project_level_variables.html
https://docs.gitlab.com/ee/api/group_level_variables.html

**Comment by louis-z** [comment]
`Variable.Raw` now exists.
