### ISSUE TITLE
During deserialization of pipeline the status "canceling" is not known and an error occurs.

### ISSUE THREAD

**Issue by anne376** [ubisoft/NGitLab#722]
Error message:  "Requested value 'canceling' was not found."

In my opinion the enum JobStatus must be extended.

**Comment by OskiKervinen-MF** [comment]
See eg. https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/2377 for where "canceling" was introduced to GitLab. It is listed at least at https://gitlab.com/gitlab-org/gitlab-runner/-/blob/main/network/remote_job_state_response.go#L16.

**Comment by OskiKervinen-MF** [comment]
Also: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/status/canceling.rb

**Comment by anne376** [comment]
Thank you very much for the quick help
