### ISSUE TITLE
Regression in 6.10.7

### ISSUE THREAD

**Issue by SamuelTrottier** [ubisoft/NGitLab#77]
Commit https://github.com/ubisoft/NGitLab/commit/947927bbb64050e4eb63f878a0f5ee3f23442395 causes a breaking change.
Some string that had the '_' character previously replaced by a '-' keep their '_' char. 

For example, before this commit, a string like the following: 'my_name' was replaced by: 'my-name'.

Now it stays : 'my_name'.

**Comment by LePtitDev** [comment]
It supports now the default GitLab behavior that does not replace `_` and `.` characters. Is this really a problem?

**Comment by meziantou** [comment]
I also think you should fix your test by making it more generic if needed (using `user1.UserName` instead of hard-coding the value)
