### ISSUE TITLE
namespaceId in ProjectCreate.cs should be an int

### ISSUE THREAD

**Issue by megla-hburdow** [ubisoft/NGitLab#797]
On: `gitLabClient.Projects.Create(new ProjectCreate { Name = "MyProjectName" });`

Exception: `Unhandled exception. NGitLab.GitLabException: GitLab server returned an error (BadRequest): {"namespace":["is not valid"]}. Original call: Post https://gitlab.mydomain.com/api/v4/projects. With data {"name":"MyProjectName","initialize_with_readme":false,"issues_enabled":false,"merge_pipelines_enabled":false,"merge_requests_enabled":false,"merge_trains_enabled":false,"snippets_enabled":false,"wiki_enabled":false,"import_url":"","visibility":"private"}`

If I understand the [GitLab API Docs.](https://docs.gitlab.com/ee/api/projects.html#create-a-project) right, the namespaceId prop in ProjectCreate.cs should be of the type int.

**Comment by louis-z** [comment]
@megla-hburdow, you're absolutely right! Thanks for reporting this. We will correct it shortly.
