### ISSUE TITLE
Refactor FileClient from v3 to v4

### ISSUE THREAD

**Issue by cyclingvegan** [ubisoft/NGitLab#82]
Hi,
First off, thanks so much for maintaining this managed API. I'm coming from the v3 API and going v4, but having a hard time with a tool we use to auto merge requests and publish them to our filesystem. This is the v3 API code which worked before, and I've got 90% of the code refactored for v4, but struggling with the filesClient and fileUpsert object. I started looking into the repoClient to see if I need to use that, but wanted some help before I go down the wrong path. The PublishAction member is just a simple local struct (defined below the the TakeActions method. The main issue seems to be that the FileData and other properties are null. Thanks for any help or direction. 

```
private static List<string> TakeActions(string basePath, IFilesClient fileClient, List<PublishAction> actions) { List<string> actionLog = new List<string>(); List<PublishAction> deferredActions = new List<PublishAction>();
        foreach (PublishAction action in actions)
        {
            if (action.Type == FilePublishActionType.Ignore)
            {
                actionLog.Add(string.Format(&quot;{0}: {1} ({2})&quot;, action.Type.ToString().ToUpper(), action.File.Path, action.Reason));
            }
            else
            {
                string publishPath = string.Format(
                    @&quot;{0}\{1}&quot;,
                    basePath,
                    action.File.Path.Replace(&#39;/&#39;, &#39;\\&#39;)
                );

                string directory = Path.GetDirectoryName(publishPath);

                switch (action.Type)
                {
                    case FilePublishActionType.Create:
                    case FilePublishActionType.Update:
                        if (!Directory.Exists(directory))
                            Directory.CreateDirectory(directory);

                        FileData file = fileClient.Get(action.File);
                        byte[] bContent = Convert.FromBase64String(file.Content);
                        File.WriteAllBytes(publishPath, bContent);

                        actionLog.Add(string.Format(&quot;{0}: {1}&quot;, action.Type.ToString().ToUpper(), action.File.Path));
                        break;
                    case FilePublishActionType.Delete:
                        if (File.Exists(publishPath))
                        {
                            File.Delete(publishPath);
                            actionLog.Add(string.Format(&quot;{0}: {1}&quot;, action.Type.ToString().ToUpper(), action.File.Path));

                            actionLog.AddRange(DeleteEmptyDirectories(basePath, directory));
                        }
                        break;
                }
            }
        }

        return actionLog;
    }

    private struct PublishAction
    {
        public FilePublishActionType Type;
        public FileData File;
        public string Reason;
    }

    private enum FilePublishActionType
    {
        Create,
        Update,
        Delete,
        Ignore
    }
```

**Comment by meziantou** [comment]
Hi,

If you are looking for usages of `FileClient`, you can have a look at the unit tests: https://github.com/ubisoft/NGitLab/blob/f0da575405d093bfdea638a10b262cae71998976/NGitLab.Tests/FilesTests.cs#L31

Also, you may want to look at the [Commit API](https://github.com/ubisoft/NGitLab/blob/main/NGitLab.Tests/RepositoryClient/RepositoryClientTests.cs#L45) to do multiple changes in one commit.

**Comment by cyclingvegan** [comment]
Thank you. This was very helpful. I am still struggling to get the content on FileData. It’s null, and I don’t see the method for Get on IFilesClient.

**Comment by meziantou** [comment]
> I don’t see the method for Get on IFilesClient.

I'm not sure to understand. The following method exists `FileData Get(string filePath, string @ref)` ([source](https://github.com/ubisoft/NGitLab/blob/main/NGitLab/IFilesClient.cs#L13), [implementation](https://github.com/ubisoft/NGitLab/blob/main/NGitLab/Impl/FilesClient.cs#L37)).

If you still have problem with this method, can you share a minimal/basic repro?

**Comment by cyclingvegan** [comment]
That's what I'm missing somehow, intellisense doesn't show me a Get() method for IFilesClient, only GetAsync().

**Comment by meziantou** [comment]
Maybe you have another `IFileClient` interface in another namespace because there is no `GetAsync` method in NGitLab. If needed, you can full qualify the type `NGitLab.IFileClient`. You can also use `typeof(IFileClient).AssemblyQualifiedName` to validate you are using the right interface at runtime.

**Comment by cyclingvegan** [comment]
Ok, sorry, I'm a doofus. There was another .NET client being used by a previous developer that was conflicting. I've removed the old reference and now am refactoring everything from scratch.

Searching through the source code, I don't see an equivalent for a Compare of two CommtiInfo objects and looking at the Diff.

**Comment by meziantou** [comment]
We have only implemented the diff from a commit https://github.com/ubisoft/NGitLab/blob/b36577b5f28f1b4ce6958081eb780d80eae46720/NGitLab/IRepositoryClient.cs#L40

Feel free to submit a pull request with the missing method 😊

**Comment by cyclingvegan** [comment]
Thanks for your assistance. All working as expected. The Diff off a Commit actually is easier. :)
