### ISSUE TITLE
Repository.GetFile returns empty image when image stored in LFS

### ISSUE THREAD

**Issue by SamuelTrottier** [ubisoft/NGitLab#91]
When fetching an image that was stored in LFS, the Repository.GetFile method returns an empty image.

**Comment by meziantou** [comment]
Does the GitLab API allow to download LFS files? Or does it only provide the LFS _placeholder_ file?

**Comment by SamuelTrottier** [comment]
I don't think the API allows to download LFS files. After a quick search, it seems that we would have to checkout the project. 

Another option might be to directly fetch the image through the `{gitlaburl}/{projectNamespace}/{projectName}/-/raw/master/{pathToFile}`, but this seems very sketchy.

**Comment by meziantou** [comment]
> Another option might be to directly fetch the image through the `{gitlaburl}/{projectNamespace}/{projectName}/-/raw/master/{pathToFile}`, but this seems very sketchy.

The authentication method is not the same for the website (cookie) and the API (token). So, it wouldn't fit NGitLab...

**Comment by SamuelTrottier** [comment]
I didn't think about it, you're right
